### ISSUE TITLE
Surelog doesn't allow to declare multiple parameters in single line

### ISSUE THREAD

**Issue by kamilrakoczy** [chipsalliance/Surelog#2340] opened 2021-12-21 13:56 UTC
TEST:
```
module dut #(parameter a = 1, b = 2, c = 3) ();

initial begin
  $display("%0d %0d %0d", a, b, c);
  if (b === 2)
    $display("PASSED");
  else
    $display("FAILED");
end

endmodule

module top();

dut #(.a(4), .b(), .c(5)) dut();

endmodule
```
Surelog fails with message:
```
Unsupported expression "<n<> u<0> t<Null_rule> p<149> s<148> l<1:1> el<1:0>> module dut #(parameter a = 1, b = 2, c = 3) ();
```
but it should pass and generate UHDM file.

**Comment by alaindargelas** [comment] 2022-01-24 01:24
The problem is reported is not correct.
It is actually the empty param overloading that is the problem.
Fixed by #2463

**Closed by alaindargelas** 2022-01-24 01:24 UTC
Labels: sv-tests
