### ISSUE TITLE
BlackParrot exponential parser time

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#2035] opened 2021-10-08 20:46 UTC
Antlr (and or the grammar) has difficulties with this code, the if else ... goes exponential in Antlr.

[ScratchPad.sv.gz](https://github.com/chipsalliance/Surelog/files/7314096/ScratchPad.sv.gz)

**Comment by alaindargelas** [comment] 2021-10-09 17:24
It does.
Yesterday I tried to add some of the tricks from sv2017 (The lookahead of one), and even remove temporarily 
primary
    : primary_literal                
//    | complex_func_call

and replace it with primary ( list_of_params )

But it did not solve the issue.

This looks like it is going to take a while to solve. In the meantime, the Blackparrot guys are trying to rework that piece of RTL.

**Comment by alaindargelas** [comment] 2021-10-09 17:28
If you can help experimenting with some of the diffs from sv2017, try to bring the minimum change in SV3_1a that would solve this issue that would help. I'll also spend some cycles in the next weeks.

**Comment by Nic30** [comment] 2021-10-10 09:29
> I got a 2x runtime factor...

The `grun` does not use semantic predicates, the speedup is probably 1 order faster.

**Comment by Thomasb81** [comment] 2021-10-10 14:29
> The `grun` does not use semantic predicates, the speedup is probably 1 order faster.

I don't understand what you say here.
The testRig/grun use the standard runtime from the jar file. Which honor semantic predicates otherwise this tool can't be use to develop grammar, even for a java application.

**Comment by Nic30** [comment] 2021-10-11 06:44
https://github.com/Nic30/hdlConvertor/blob/master/grammars/sv2017Parser.g4#L402

I do not remember specifics, but how does `_input->LA(1)` compile to java then?

**Comment by Thomasb81** [comment] 2021-10-13 21:59
> If you can help experimenting with some of the diffs from sv2017, try to bring the minimum change in SV3_1a that would solve this issue that would help.

By commenting `identifier `alternative in `primary_literal `: 

```
primary_literal  
    : number                   
    | time_literal             
    | unbased_unsized_literal  
    | string_value
//    | identifier
    ; 
```
I pass from 490 Ambiguity to 239 on ScratchPad.sv testcase. However from runtime perspective the gain is still marginal (may be 3s on my workstation with testRig ). Also even if this a small change the resulting matched rule is different and break the regression. 

I think that what you request or expect could not be achieve : removing ambiguity, require to change the grammar. Any ambiguity related to hierachical/scope /identifier /function/method call (the one who are currently killing the perf in the current testcase) will have serious impact on existing code database because they are almost every where...

Note : I achieve a similar result by removing `primary_literal` ( by inlining the rule and removing the simplest aternative)  ... the impact was even worse : it break the compilation :  `VObjectType::slPrimary_literal` disappear. I was not able to identify how to fix the code.

**Comment by alaindargelas** [comment] 2021-10-13 22:38
@Thomasb81, assume we can change the code base, the first order should be to identify the ambiguities that surface in this test

**Comment by Thomasb81** [comment] 2021-10-21 06:38
[SV3_1aParser.g4.tar.gz](https://github.com/chipsalliance/Surelog/files/7386396/SV3_1aParser.g4.tar.gz)

With this java version of the grammar, I was able : 
- to pass from 565 to 241 `reportAttemptingFullContext`.
- to pass from 467 to 138 `reportAmbiguity`
compare to the one currently in database.

I am still not able to observe a  significant and noticeable performance gain on this testcase ... probably antlr runtime has some threshold effect ...

I am not always sure that change in the grammar are legal and will preserve the correct parsing of some systemVerilog construction, because all possible syntax are not expose in this testcase. Sometime it is difficult to identify the usecase from an allowed syntax or you are simply not aware or LRM is wrong...
It is not easy to re-use other surelog test because they may contain preprocessing directive not directly compatible with this grammar.

Remaining major and expected contributor of ambiguity are still around hierarchical identifier/function/method/system call where the tool seem to loose efficiency in order to identify the right grammar that match the statement.

**Comment by Thomasb81** [comment] 2021-11-06 11:38
Here is an article on antlr performance
https://tomassetti.me/improving-the-performance-of-an-antlr-parser/

I observe that when this grammar is run through vscode / https://github.com/mike-lischke/vscode-antlr4 (v2.2.4) with the appropriate change to conform predicate to javascript runtime. (The one in place can even be removed to ease runtime 
switch)

The testcase is process in few second ! against still about 1 minute 30s with the java 4.9.2 runtime on my computer...
I did not expect that at all...

**Comment by Thomasb81** [comment] 2022-12-09 21:56
Hello

I give a re-try of this issue against b08d86c5baa54f6cdb03ad9dcf141f338f94e254

```
$ time ./surelog -parse  ScratchPad.sv
...
[  FATAL] : 0
[ SYNTAX] : 0
[  ERROR] : 1
[WARNING] : 2
[   NOTE] : 5

real	0m0,061s
user	0m0,053s
sys	0m0,008s
```

The runtime seems now quite descent. I would propose to close this issue.

**Closed** 2023-05-07 05:38 UTC
Labels: blackparrot
